# Generated by Django 4.1.2 on 2022-10-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_rename_song_lyric_song_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='song_id',
            new_name='song',
        ),
        migrations.AlterField(
            model_name='lyric',
            name='content',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='song',
            name='artiste_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='likes',
            field=models.PositiveIntegerField(),
        ),
    ]
