# Generated by Django 4.1.2 on 2022-10-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_song_id_alter_artiste_age_alter_lyric_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
